orbs:
  pypi: pennlabs/pypi-tools@0.0.4
version: 2.1
workflows:
  build-and-publish:
    jobs:
      - pypi/test:
          filters:
            tags:
              only: /.*/
      - pypi/publish:
          context: pypi-publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/[0-9]+(\.[0-9]+)*/'
          requires:
            - pypi/test